#!/usr/bin/env python3
"""
Script to update schema.json with physics-based positioning data
Based on the comprehensive trick table
"""

# Table data from the image
TRICK_PHYSICS = {
    "makio": {
        "back_foot_degree": None,
        "front_foot_degree": None,
        "back_foot_knee": "NA",
        "front_foot_knee": "NA",
        "back_foot_hblock_pointing": "NA",
        "front_foot_hblock_pointing": "NA",
        "topside_or_regular": "regular",
        "can_be_grabbed": True,
        "cross_grab": True,
        "crossed_foot": "NA",
        "spin_multiplier": 180,
        "balance_point": "on top",
        "h_block_type": "NA",
    },
    "fishbrain": {  # topside makio
        "back_foot_degree": 0,
        "front_foot_degree": None,
        "back_foot_knee": "neutral",
        "front_foot_knee": "NA",
        "back_foot_hblock_pointing": "NA",
        "front_foot_hblock_pointing": "NA",
        "topside_or_regular": "topside",
        "can_be_grabbed": True,
        "cross_grab": True,
        "crossed_foot": "NA",
        "spin_multiplier": 180,
        "balance_point": "on top",
        "h_block_type": "NA",
    },
    "soul": {
        "back_foot_degree": 0,
        "front_foot_degree": -90,
        "back_foot_knee": "bent towards back",
        "front_foot_knee": "NA",
        "back_foot_hblock_pointing": "inner pointing towards back",
        "front_foot_hblock_pointing": "NA",
        "topside_or_regular": "regular",
        "can_be_grabbed": False,
        "cross_grab": False,
        "crossed_foot": "NA",
        "spin_multiplier": 180,
        "balance_point": "more back",
        "h_block_type": "front",
    },
    "topsoul": {
        "back_foot_degree": 0,
        "front_foot_degree": -90,
        "back_foot_knee": "bent towards back",
        "front_foot_knee": "NA",
        "back_foot_hblock_pointing": "inner pointing towards back",
        "front_foot_hblock_pointing": "NA",
        "topside_or_regular": "topside",
        "can_be_grabbed": False,
        "cross_grab": False,
        "crossed_foot": "NA",
        "spin_multiplier": 180,
        "balance_point": "more back",
        "h_block_type": "front",
    },
    "torque_soul": {
        "back_foot_degree": 0,
        "front_foot_degree": -90,
        "back_foot_knee": "bent away back",
        "front_foot_knee": "NA",
        "back_foot_hblock_pointing": "inner pointing away back",
        "front_foot_hblock_pointing": "NA",
        "topside_or_regular": "regular",
        "can_be_grabbed": False,
        "cross_grab": False,
        "crossed_foot": "NA",
        "spin_multiplier": 180,
        "balance_point": "more front",
        "h_block_type": "front",
    },
    "top_torque_soul": {
        "back_foot_degree": 0,
        "front_foot_degree": -90,
        "back_foot_knee": "bent away back",
        "front_foot_knee": "NA",
        "back_foot_hblock_pointing": "inner pointing away back",
        "front_foot_hblock_pointing": "NA",
        "topside_or_regular": "topside",
        "can_be_grabbed": False,
        "cross_grab": False,
        "crossed_foot": "NA",
        "spin_multiplier": 180,
        "balance_point": "more front",
        "h_block_type": "front",
    },
    "acid_soul": {
        "back_foot_degree": 0,
        "front_foot_degree": -90,
        "back_foot_knee": "bent towards back",
        "front_foot_knee": "NA",
        "back_foot_hblock_pointing": "outer pointing towards back",
        "front_foot_hblock_pointing": "NA",
        "topside_or_regular": "regular",
        "can_be_grabbed": False,
        "cross_grab": False,
        "crossed_foot": "NA",
        "spin_multiplier": 180,
        "balance_point": "more back",
        "h_block_type": "front",
    },
    "topacid": {
        "back_foot_degree": 0,
        "front_foot_degree": -90,
        "back_foot_knee": "bent towards back",
        "front_foot_knee": "NA",
        "back_foot_hblock_pointing": "outer pointing towards back",
        "front_foot_hblock_pointing": "NA",
        "topside_or_regular": "topside",
        "can_be_grabbed": False,
        "cross_grab": False,
        "crossed_foot": "NA",
        "spin_multiplier": 180,
        "balance_point": "more back",
        "h_block_type": "front",
    },
    "pornstar": {
        "back_foot_degree": -90,
        "front_foot_degree": 0,
        "back_foot_knee": "bent towards front",
        "front_foot_knee": "neutral",
        "back_foot_hblock_pointing": "outer pointing towards front",
        "front_foot_hblock_pointing": "NA",
        "topside_or_regular": "regular",
        "can_be_grabbed": False,
        "cross_grab": False,
        "crossed_foot": "NA",
        "spin_multiplier": 180,
        "balance_point": "more front",
        "h_block_type": "back",
    },
    "top_pornstar": {
        "back_foot_degree": -90,
        "front_foot_degree": 0,
        "back_foot_knee": "bent towards front",
        "front_foot_knee": "neutral",
        "back_foot_hblock_pointing": "outer pointing towards front",
        "front_foot_hblock_pointing": "NA",
        "topside_or_regular": "topside",
        "can_be_grabbed": False,
        "cross_grab": False,
        "crossed_foot": "NA",
        "spin_multiplier": 180,
        "balance_point": "more front",
        "h_block_type": "back",
    },
    "mizou": {
        "back_foot_degree": -90,
        "front_foot_degree": 0,
        "back_foot_knee": "bent towards front",
        "front_foot_knee": "neutral",
        "back_foot_hblock_pointing": "inner pointing towards front",
        "front_foot_hblock_pointing": "NA",
        "topside_or_regular": "regular",
        "can_be_grabbed": False,
        "cross_grab": False,
        "crossed_foot": "NA",
        "spin_multiplier": 180,
        "balance_point": "more front",
        "h_block_type": "back",
    },
    "sweatstance": {  # topside mizou
        "back_foot_degree": -90,
        "front_foot_degree": 0,
        "back_foot_knee": "bent towards front",
        "front_foot_knee": "neutral",
        "back_foot_hblock_pointing": "inner pointing towards front",
        "front_foot_hblock_pointing": "NA",
        "topside_or_regular": "topside",
        "can_be_grabbed": False,
        "cross_grab": False,
        "crossed_foot": "NA",
        "spin_multiplier": 180,
        "balance_point": "more front",
        "h_block_type": "back",
    },
    "mistrial": {
        "back_foot_degree": -90,
        "front_foot_degree": 0,
        "back_foot_knee": "bent away front",
        "front_foot_knee": "neutral",
        "back_foot_hblock_pointing": "inner pointing towards front",
        "front_foot_hblock_pointing": "NA",
        "topside_or_regular": "regular",
        "can_be_grabbed": False,
        "cross_grab": False,
        "crossed_foot": "NA",
        "spin_multiplier": 180,
        "balance_point": "more front",
        "h_block_type": "back",
    },
    "top_mistrial": {
        "back_foot_degree": -90,
        "front_foot_degree": 0,
        "back_foot_knee": "bent away front",
        "front_foot_knee": "neutral",
        "back_foot_hblock_pointing": "inner pointing towards front",
        "front_foot_hblock_pointing": "NA",
        "topside_or_regular": "topside",
        "can_be_grabbed": False,
        "cross_grab": False,
        "crossed_foot": "NA",
        "spin_multiplier": 180,
        "balance_point": "more front",
        "h_block_type": "back",
    },
    # X grinds
    "x_grind": {
        "back_foot_degree": 0,
        "front_foot_degree": 0,
        "back_foot_knee": "neutral",
        "front_foot_knee": "neutral",
        "back_foot_hblock_pointing": "NA",
        "front_foot_hblock_pointing": "NA",
        "topside_or_regular": "regular",
        "can_be_grabbed": False,
        "cross_grab": False,
        "crossed_foot": "NA",
        "spin_multiplier": 180,
        "balance_point": "on top",
        "h_block_type": "NA",
    },
    "topside_x_grind": {
        "back_foot_degree": 0,
        "front_foot_degree": 0,
        "back_foot_knee": "neutral",
        "front_foot_knee": "neutral",
        "back_foot_hblock_pointing": "NA",
        "front_foot_hblock_pointing": "NA",
        "topside_or_regular": "topside",
        "can_be_grabbed": False,
        "cross_grab": False,
        "crossed_foot": "NA",
        "spin_multiplier": 180,
        "balance_point": "on top",
        "h_block_type": "NA",
    },
    # Full H-block tricks
    "frontside": {
        "back_foot_degree": 90,
        "front_foot_degree": 90,
        "back_foot_knee": "bent towards front",
        "front_foot_knee": "bent towards back",
        "back_foot_hblock_pointing": "inner pointing towards front",
        "front_foot_hblock_pointing": "inner pointing towards back",
        "topside_or_regular": "NA",
        "can_be_grabbed": False,
        "cross_grab": False,
        "crossed_foot": "NA",
        "spin_multiplier": 90,
        "balance_point": "on top",
        "h_block_type": "both",
    },
    "backslide": {
        "back_foot_degree": -90,
        "front_foot_degree": -90,
        "back_foot_knee": "bent towards front",
        "front_foot_knee": "bent towards back",
        "back_foot_hblock_pointing": "inner pointing towards front",
        "front_foot_hblock_pointing": "inner pointing towards back",
        "topside_or_regular": "NA",
        "can_be_grabbed": False,
        "cross_grab": False,
        "crossed_foot": "NA",
        "spin_multiplier": 90,
        "balance_point": "on top",
        "h_block_type": "both",
    },
    "frontside_royale": {
        "back_foot_degree": 90,
        "front_foot_degree": 90,
        "back_foot_knee": "bent away front",
        "front_foot_knee": "bent towards back",
        "back_foot_hblock_pointing": "inner pointing away front",
        "front_foot_hblock_pointing": "inner pointing towards back",
        "topside_or_regular": "NA",
        "can_be_grabbed": False,
        "cross_grab": False,
        "crossed_foot": "NA",
        "spin_multiplier": 90,
        "balance_point": "more front",
        "h_block_type": "both",
    },
    "backside_royale": {
        "back_foot_degree": -90,
        "front_foot_degree": -90,
        "back_foot_knee": "bent towards front",
        "front_foot_knee": "bent away back",
        "back_foot_hblock_pointing": "inner pointing towards front",
        "front_foot_hblock_pointing": "inner pointing away back",
        "topside_or_regular": "NA",
        "can_be_grabbed": False,
        "cross_grab": False,
        "crossed_foot": "NA",
        "spin_multiplier": 90,
        "balance_point": "more front",
        "h_block_type": "both",
    },
    "frontside_farv": {
        "back_foot_degree": 90,
        "front_foot_degree": 90,
        "back_foot_knee": "bent towards front",
        "front_foot_knee": "bent away back",
        "back_foot_hblock_pointing": "inner pointing towards front",
        "front_foot_hblock_pointing": "inner pointing away back",
        "topside_or_regular": "NA",
        "can_be_grabbed": False,
        "cross_grab": False,
        "crossed_foot": "NA",
        "spin_multiplier": 90,
        "balance_point": "more back",
        "h_block_type": "both",
    },
    "backside_farv": {
        "back_foot_degree": -90,
        "front_foot_degree": -90,
        "back_foot_knee": "bent away front",
        "front_foot_knee": "bent towards back",
        "back_foot_hblock_pointing": "inner pointing away front",
        "front_foot_hblock_pointing": "inner pointing towards back",
        "topside_or_regular": "NA",
        "can_be_grabbed": False,
        "cross_grab": False,
        "crossed_foot": "NA",
        "spin_multiplier": 90,
        "balance_point": "more back",
        "h_block_type": "both",
    },
    # Single foot h-block tricks
    "frontside_torque": {
        "back_foot_degree": None,
        "front_foot_degree": -90,
        "back_foot_knee": "NA",
        "front_foot_knee": "bent away back",
        "back_foot_hblock_pointing": "NA",
        "front_foot_hblock_pointing": "inner pointing away back",
        "topside_or_regular": "NA",
        "can_be_grabbed": True,
        "cross_grab": True,
        "crossed_foot": "NA",
        "spin_multiplier": 90,
        "balance_point": "more back",
        "h_block_type": "front",
    },
    "backside_torque": {
        "back_foot_degree": None,
        "front_foot_degree": -90,
        "back_foot_knee": "NA",
        "front_foot_knee": "bent away back",
        "back_foot_hblock_pointing": "NA",
        "front_foot_hblock_pointing": "inner pointing away back",
        "topside_or_regular": "NA",
        "can_be_grabbed": True,
        "cross_grab": True,
        "crossed_foot": "NA",
        "spin_multiplier": 90,
        "balance_point": "more back",
        "h_block_type": "front",
    },
    "frontside_unity": {
        "back_foot_degree": 90,
        "front_foot_degree": 90,
        "back_foot_knee": "bent towards front",
        "front_foot_knee": "bent towards back",
        "back_foot_hblock_pointing": "outer pointing towards front",
        "front_foot_hblock_pointing": "outer pointing towards back",
        "topside_or_regular": "NA",
        "can_be_grabbed": False,
        "cross_grab": False,
        "crossed_foot": "front foot",
        "spin_multiplier": 90,
        "balance_point": "on top",
        "h_block_type": "both",
    },
    "backside_unity": {
        "back_foot_degree": -90,
        "front_foot_degree": -90,
        "back_foot_knee": "bent towards front",
        "front_foot_knee": "bent towards back",
        "back_foot_hblock_pointing": "outer pointing towards front",
        "front_foot_hblock_pointing": "outer pointing towards back",
        "topside_or_regular": "NA",
        "can_be_grabbed": False,
        "cross_grab": False,
        "crossed_foot": "front foot",
        "spin_multiplier": 90,
        "balance_point": "on top",
        "h_block_type": "both",
    },
    # Crossed foot tricks
    "frontside_savannah": {
        "back_foot_degree": 90,
        "front_foot_degree": -90,
        "back_foot_knee": "bent towards front",
        "front_foot_knee": "bent towards back",
        "back_foot_hblock_pointing": "outer pointing towards front",
        "front_foot_hblock_pointing": "outer pointing towards back",
        "topside_or_regular": "NA",
        "can_be_grabbed": False,
        "cross_grab": False,
        "crossed_foot": "back foot",
        "spin_multiplier": 90,
        "balance_point": "on top",
        "h_block_type": "both",
    },
    "backside_savannah": {
        "back_foot_degree": 90,
        "front_foot_degree": -90,
        "back_foot_knee": "bent towards front",
        "front_foot_knee": "bent towards back",
        "back_foot_hblock_pointing": "outer pointing towards front",
        "front_foot_hblock_pointing": "outer pointing towards back",
        "topside_or_regular": "NA",
        "can_be_grabbed": False,
        "cross_grab": False,
        "crossed_foot": "back foot",
        "spin_multiplier": 90,
        "balance_point": "on top",
        "h_block_type": "both",
    },
    # Single foot h-block back foot tricks
    "frontside_fastslide": {
        "back_foot_degree": None,
        "front_foot_degree": -90,
        "back_foot_knee": "NA",
        "front_foot_knee": "bent towards back",
        "back_foot_hblock_pointing": "NA",
        "front_foot_hblock_pointing": "inner pointing towards back",
        "topside_or_regular": "NA",
        "can_be_grabbed": True,
        "cross_grab": True,
        "crossed_foot": "NA",
        "spin_multiplier": 90,
        "balance_point": "more front",
        "h_block_type": "back",
    },
    "backside_fastslide": {
        "back_foot_degree": None,
        "front_foot_degree": -90,
        "back_foot_knee": "NA",
        "front_foot_knee": "bent towards back",
        "back_foot_hblock_pointing": "NA",
        "front_foot_hblock_pointing": "inner pointing towards back",
        "topside_or_regular": "NA",
        "can_be_grabbed": True,
        "cross_grab": True,
        "crossed_foot": "NA",
        "spin_multiplier": 90,
        "balance_point": "more front",
        "h_block_type": "front",
    },
    "frontside_pudslide": {
        "back_foot_degree": 90,
        "front_foot_degree": None,
        "back_foot_knee": "bent towards front",
        "front_foot_knee": "NA",
        "back_foot_hblock_pointing": "inner pointing towards front",
        "front_foot_hblock_pointing": "NA",
        "topside_or_regular": "NA",
        "can_be_grabbed": True,
        "cross_grab": True,
        "crossed_foot": "NA",
        "spin_multiplier": 90,
        "balance_point": "more front",
        "h_block_type": "back",
    },
    "backside_pudslide": {
        "back_foot_degree": -90,
        "front_foot_degree": None,
        "back_foot_knee": "bent towards front",
        "front_foot_knee": "NA",
        "back_foot_hblock_pointing": "inner pointing towards front",
        "front_foot_hblock_pointing": "NA",
        "topside_or_regular": "NA",
        "can_be_grabbed": True,
        "cross_grab": True,
        "crossed_foot": "NA",
        "spin_multiplier": 90,
        "balance_point": "more back",
        "h_block_type": "back",
    },
}

if __name__ == "__main__":
    import json

    print(json.dumps(TRICK_PHYSICS, indent=2))
